### ISSUE TITLE
REDIRECT_URI 是什么

### ISSUE THREAD

**Issue by jacquesqiao** [dueros/dcs-sdk-js#3]
请问申请 access_token 用到的REDIRECT_URI 是什么？

**Comment by rench** [comment]
I think `REDIRECT_URI ` is the config  in your baidu system App control panel,

**Comment by wwwppp0801** [comment]
可以在 http://developer.dueros.baidu.com/ 申请开发者账号，之后就可以创建应用。

对于每个应用，有一个oauth账号，有对应的client_id、client_secret，也可以配置oauth账号的redirect_uri（用户授权后跳转到的地址）

百度支持的oauth协议，文档在 http://developer.baidu.com/wiki/index.php?title=docs/oauth。（一般的开发者应用不能用来访问dueros，必须是在developer.dueros.baidu.com里申请的）
