### ISSUE TITLE
dueros of js sometimes will be break by it's own sound~

### ISSUE THREAD

**Issue by jacquesqiao** [dueros/dcs-sdk-js#4]
在播放过程中会被自己的声音打断，然后进入“你好...抱歉我不太确定你说了什么...你好...” 的无限循环中~

**Comment by boilingwater** [comment]
我也遇到这个问题，感觉是有几个人同时再回答我

**Comment by jacquesqiao** [comment]
对，感觉有多线程的问题

**Comment by wwwppp0801** [comment]
可能在不同的场景下，唤醒调的过于灵敏，建议pull一下新的代码，然后调整下./snowboy.js  里面的models.add({
  file:  __dirname+'/snowboy/resources/xiaoduxiaodu.umdl',
  sensitivity: '0.9',
  hotwords : '小度小度'
});
这段，重点是把sensitivity降低一点
