### ISSUE TITLE
使用centos 系统可以吗？-费元星

### ISSUE THREAD

**Issue by F971751392** [dueros/dcs-sdk-js#6]
如题使用centos 系统可以吗？
系统使用win，虚机中安装的centos 可以吗？

-费元星

**Comment by wwwppp0801** [comment]
centos肯定能用。虚机我不太确定，主要是不知道alsa和声卡驱动能不能work

**Comment by Ihuzb** [comment]
每次听音都需要回车才可以吗？

**Comment by F971751392** [comment]
不需要吧@Ihuzb
