### ISSUE TITLE
修改码率后AudioPlayer无法播放

### ISSUE THREAD

**Issue by Namco0816** [dueros/dcs-sdk-js#8]
recorder默认的是32bit 44100的码率导致播放语速过快，修改为16bit 48000的码率后，voiceoutput可以正常语速播放，然而audioplayer无法播放歌曲，而play status 显示的是正在播放
---以下内容2018-3-19更新
我在dcs_client.js中，将 原本的“用RecorderWrapper包一下，是因为怕播放指令执行的时候，管道已经输出了一点东西了，复用一下RecorderWrapper的缓存功能”重新改为了之前版本没有用recordwrapper的代码，这个时候audioplayer开始工作了，可以正常的输出音频声音，但是voiceoutput停止了输出，类似于 “小度小度，今天的天气”等的回答全都没了声音。

**Comment by wwwppp0801** [comment]
audioplayer和recorder是没有关系的。  audioplayer只用来播放音乐，依赖了mplayer（或者mplayer2）。    建议不要改js代码，参考下dcs_config_example/下的几个默认配置就好。

**Comment by Namco0816** [comment]
好的谢谢！我发现是我硬件这边出了问题，确实正常情况下是不需要修改recorder的，谢谢！
